"credentials-file": "modules/cloudflare-tunnel/config/tf-docker-tunnel-token.json"
"ingress":
- "hostname": "fabricesemti.dev"
  "service": "http://10.0.40.20:11111"
- "hostname": "grafana.fabricesemti.dev"
  "service": "http://10.0.40.20:3000"
- "hostname": "hass.fabricesemti.dev"
  "service": "http://10.0.40.21:8123"
- "hostname": "jellyfin.fabricesemti.dev"
  "service": "http://10.0.40.20:8096"
- "hostname": "jellyseerr.fabricesemti.dev"
  "service": "http://10.0.40.20:5056"
- "hostname": "kestra.fabricesemti.dev"
  "service": "http://10.0.40.21:8080"
- "hostname": "n8n.fabricesemti.dev"
  "service": "http://10.0.40.21:5678"
- "hostname": "overseerr.fabricesemti.dev"
  "service": "http://10.0.40.20:5055"
- "hostname": "plex.fabricesemti.dev"
  "service": "http://10.0.40.2:32400"
- "hostname": "prometheus.fabricesemti.dev"
  "service": "http://10.0.40.20:9090"
- "hostname": "prowlarr.fabricesemti.dev"
  "service": "http://10.0.40.20:9696"
- "hostname": "radarr.fabricesemti.dev"
  "service": "http://10.0.40.20:7878"
- "hostname": "sabnzbd.fabricesemti.dev"
  "service": "http://10.0.40.20:18080"
- "hostname": "sonarr.fabricesemti.dev"
  "service": "http://10.0.40.20:8989"
- "hostname": null
  "service": "http_status:404"
"tunnel": "395192e9-61e6-46e3-89df-ee5261753621"
